// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBn0-aVYZDR--smvT_CC1ayaBhxIwRiH4',
    appId: '1:839044245736:web:1fda46c78fecbd226c015d',
    messagingSenderId: '839044245736',
    projectId: 'rssi-test-df593',
    authDomain: 'rssi-test-df593.firebaseapp.com',
    storageBucket: 'rssi-test-df593.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn-GMN-id-AxBvUbhIbjh-nQ5y3-1BNqI',
    appId: '1:839044245736:android:62121ce7c163163e6c015d',
    messagingSenderId: '839044245736',
    projectId: 'rssi-test-df593',
    storageBucket: 'rssi-test-df593.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBn0-aVYZDR--smvT_CC1ayaBhxIwRiH4',
    appId: '1:839044245736:web:88b2eb042da1c6496c015d',
    messagingSenderId: '839044245736',
    projectId: 'rssi-test-df593',
    authDomain: 'rssi-test-df593.firebaseapp.com',
    storageBucket: 'rssi-test-df593.firebasestorage.app',
  );
}
